// Code generated by goyacc -l -o sql.go sql.y. DO NOT EDIT.
package parser

import __yyfmt__ "fmt"

func setParseTree(yylex yyLexer, stmt Statement) {
	yylex.(*Lexer).ParseTree = stmt
}

type yySymType struct {
	yys       int
	str       string
	num       int
	statement Statement
	strs      []string
	cond      *Condition
	conds     []*Condition
	where     *Where
}

const LEX_ERROR = 57346
const NAME = 57347
const NUMBER = 57348
const STRING = 57349
const INTNUM = 57350
const APPROXNUM = 57351
const OR = 57352
const AND = 57353
const NOT = 57354
const RELATION = 57355
const OPERATOR = 57356
const ASTERISK = 57357
const ALL = 57358
const AMMSC = 57359
const ANY = 57360
const ASC = 57361
const AS = 57362
const AUTHORIZATION = 57363
const AVG = 57364
const BETWEEN = 57365
const BY = 57366
const CHARACTER = 57367
const CHECK = 57368
const CLOSE = 57369
const COMMIT = 57370
const CONTINUE = 57371
const CREATE = 57372
const CURRENT = 57373
const COMMA = 57374
const CURSOR = 57375
const DECIMAL = 57376
const DECLARE = 57377
const DEFAULT = 57378
const DELETE = 57379
const DESC = 57380
const DISTINCT = 57381
const DOUBLE = 57382
const ESCAPE = 57383
const EXISTS = 57384
const FETCH = 57385
const FLOAT = 57386
const FOR = 57387
const FOREIGN = 57388
const FOUND = 57389
const FROM = 57390
const GOTO = 57391
const GRANT = 57392
const GROUP = 57393
const HAVING = 57394
const IN = 57395
const INDICATOR = 57396
const INSERT = 57397
const INTEGER = 57398
const INTO = 57399
const IS = 57400
const MIN = 57401
const MAX = 57402
const KEY = 57403
const LANGUAGE = 57404
const LIKE = 57405
const NULLX = 57406
const NUMERIC = 57407
const OF = 57408
const ON = 57409
const OPEN = 57410
const OPTION = 57411
const ORDER = 57412
const PARAMETER = 57413
const PRECISION = 57414
const PRIMARY = 57415
const PRIVILEGES = 57416
const PROCEDURE = 57417
const PUBLIC = 57418
const REAL = 57419
const REFERENCES = 57420
const ROLLBACK = 57421
const SCHEMA = 57422
const SELECT = 57423
const SET = 57424
const SMALLINT = 57425
const SOME = 57426
const SQLCODE = 57427
const SQLERROR = 57428
const SUM = 57429
const TABLE = 57430
const TO = 57431
const UNION = 57432
const UNIQUE = 57433
const UPDATE = 57434
const USER = 57435
const VALUES = 57436
const VIEW = 57437
const WHENEVER = 57438
const WHERE = 57439
const WITH = 57440
const WORK = 57441

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"LEX_ERROR",
	"NAME",
	"NUMBER",
	"STRING",
	"INTNUM",
	"APPROXNUM",
	"OR",
	"AND",
	"NOT",
	"RELATION",
	"OPERATOR",
	"'.'",
	"ASTERISK",
	"ALL",
	"AMMSC",
	"ANY",
	"ASC",
	"AS",
	"AUTHORIZATION",
	"AVG",
	"BETWEEN",
	"BY",
	"CHARACTER",
	"CHECK",
	"CLOSE",
	"COMMIT",
	"CONTINUE",
	"CREATE",
	"CURRENT",
	"COMMA",
	"CURSOR",
	"DECIMAL",
	"DECLARE",
	"DEFAULT",
	"DELETE",
	"DESC",
	"DISTINCT",
	"DOUBLE",
	"ESCAPE",
	"EXISTS",
	"FETCH",
	"FLOAT",
	"FOR",
	"FOREIGN",
	"FOUND",
	"FROM",
	"GOTO",
	"GRANT",
	"GROUP",
	"HAVING",
	"IN",
	"INDICATOR",
	"INSERT",
	"INTEGER",
	"INTO",
	"IS",
	"MIN",
	"MAX",
	"KEY",
	"LANGUAGE",
	"LIKE",
	"NULLX",
	"NUMERIC",
	"OF",
	"ON",
	"OPEN",
	"OPTION",
	"ORDER",
	"PARAMETER",
	"PRECISION",
	"PRIMARY",
	"PRIVILEGES",
	"PROCEDURE",
	"PUBLIC",
	"REAL",
	"REFERENCES",
	"ROLLBACK",
	"SCHEMA",
	"SELECT",
	"SET",
	"SMALLINT",
	"SOME",
	"SQLCODE",
	"SQLERROR",
	"SUM",
	"TABLE",
	"TO",
	"UNION",
	"UNIQUE",
	"UPDATE",
	"USER",
	"VALUES",
	"VIEW",
	"WHENEVER",
	"WHERE",
	"WITH",
	"WORK",
	"'('",
	"')'",
	"','",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 28

var yyAct = [...]int{
	13, 4, 8, 17, 20, 23, 22, 21, 6, 26,
	27, 18, 19, 28, 24, 15, 7, 11, 10, 9,
	3, 2, 1, 12, 16, 25, 5, 14,
}

var yyPact = [...]int{
	-81, -1000, -1000, -1000, 11, -31, -1000, -1000, 11, -98,
	10, -1000, -1000, 6, -1000, -11, -4, -1000, -7, -8,
	9, 6, 4, 7, -1000, -1000, -1000, -1000, -1000,
}

var yyPgo = [...]int{
	0, 27, 8, 26, 3, 24, 23, 22, 21, 20,
	19, 19, 19, 19, 19, 19, 19, 19, 19, 19,
	19, 19, 19, 19, 19, 19, 19, 19, 19, 19,
	19, 19, 19, 19, 19, 19, 19, 19,
}

var yyR1 = [...]int{
	0, 7, 11, 13, 13, 14, 14, 15, 15, 16,
	18, 18, 19, 19, 20, 23, 23, 24, 24, 21,
	3, 3, 17, 2, 25, 25, 8, 26, 27, 28,
	29, 30, 30, 31, 31, 33, 34, 9, 9, 10,
	6, 5, 5, 4, 4, 4, 32, 32, 32, 35,
	35, 35, 36, 36, 36, 1, 1, 22, 22, 22,
	37, 12,
}

var yyR2 = [...]int{
	0, 1, 5, 0, 1, 1, 2, 1, 1, 6,
	1, 3, 1, 1, 3, 0, 2, 2, 3, 4,
	1, 3, 4, 1, 0, 3, 1, 1, 2, 5,
	4, 1, 3, 1, 1, 1, 1, 4, 3, 2,
	2, 1, 3, 3, 3, 3, 1, 1, 1, 1,
	2, 3, 1, 1, 1, 1, 3, 1, 1, 1,
	1, 1,
}

var yyChk = [...]int{
	-1000, -7, -8, -9, 82, -3, -2, 5, 33, -10,
	49, -2, -6, 98, -1, 5, -5, -4, 5, 6,
	15, 11, 13, 13, 5, -4, 5, 6, 6,
}

var yyDef = [...]int{
	0, -2, 1, 26, 0, 0, 20, 23, 0, 38,
	0, 21, 37, 0, 39, 55, 40, 41, 0, 0,
	0, 0, 0, 0, 56, 42, 43, 44, 45,
}

var yyTok1 = [...]int{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	101, 102, 3, 3, 103, 3, 15,
}

var yyTok2 = [...]int{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 16, 17, 18, 19, 20, 21, 22,
	23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
	33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
	43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
	53, 54, 55, 56, 57, 58, 59, 60, 61, 62,
	63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
	73, 74, 75, 76, 77, 78, 79, 80, 81, 82,
	83, 84, 85, 86, 87, 88, 89, 90, 91, 92,
	93, 94, 95, 96, 97, 98, 99, 100,
}

var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			setParseTree(yylex, yyDollar[1].statement)
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.strs = []string{yyDollar[1].str}
		}
	case 21:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.strs = append(yyDollar[1].strs, yyDollar[3].str)
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.str = yyDollar[1].str
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.statement = yyDollar[1].statement
		}
	case 37:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.statement = NewSelect(yyDollar[2].strs, yyDollar[3].statement, yyDollar[4].where)
		}
	case 38:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.statement = NewSelect(yyDollar[2].strs, yyDollar[3].statement, nil)
		}
	case 39:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.statement = NewFrom(yyDollar[2].str)
		}
	case 40:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.where = NewWhere(yyDollar[2].conds)
		}
	case 41:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.conds = []*Condition{yyDollar[1].cond}
		}
	case 42:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.conds = append(yyDollar[1].conds, yyDollar[3].cond)
		}
	case 43:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.cond = NewCondition(yyDollar[2].str, yyDollar[1].str, yyDollar[3].str)
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.cond = NewCondition(yyDollar[2].str, yyDollar[1].str, yyDollar[3].num)
		}
	case 45:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.cond = NewCondition(yyDollar[2].str, yyDollar[1].num, yyDollar[3].num)
		}
	case 55:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.str = yyDollar[1].str
		}
	case 56:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.str = yyDollar[1].str
		}
	}
	goto yystack /* stack new state and value */
}
